version: '3'

services:
  app:
    build: .
    container_name: rodabelem_service
    restart: always
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roda_belem_test
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306  
    volumes:
      - .docker/mysql:/var/lib/mysql